name: Make a new binary build

on:
  push:
    tags:
      - 'v*'
  pull-request:
  workflow_dispatch:

jobs:

  build-and-make:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Prepare theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-src: 'https://github.com/roothide/theos'

      - name: Replace SDKs
        run: |
          rm -rf ${{ github.workspace }}/theos/sdks
          wget --no-verbose https://github.com/chrisharper22/sdks/archive/refs/heads/main.zip
          TMP=$(mktemp -d)
          7z x main.zip -o$TMP
          mkdir ${{ github.workspace }}/theos/sdks
          mv $TMP/sdks-main/*.sdk ${{ github.workspace }}/theos/sdks
          rm -rf main.zip $TMP

      - name: Build
        run: |
          make package FINAL_PACKAGE=1 THEOS_PACKAGE_SCHEME=rootless
          make package FINAL_PACKAGE=1 THEOS_PACKAGE_SCHEME=rootful
          make package FINAL_PACKAGE=1

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: "Swifile"
          path: ${{ github.workspace }}/packages/*.deb
